version: "3.7"
services:
  flyway:
    image: flyway/flyway:6-alpine
    volumes:
      - ./services/flyway/sql:/flyway/sql
      - ./services/flyway/conf:/flyway/conf
    network_mode: "host"
    depends_on:
      - mysql
    command: -connectRetries=60 migrate
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: programmingroad
    volumes:
      - ./services/mysql/volume:/var/lib/mysql
    network_mode: "host"
    restart: always