version: "3.7"
services:
  flyway:
    image: flyway/flyway:6-alpine
    command: -url=jdbc:mysql://mysql -schemas=programmingroad -user=root -password=root -connectRetries=60 migrate
    volumes:
      - ../volumes/flyway/sql:/flyway/sql
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ../volumes/mysql:/var/lib/mysql
    network_mode: "host"
    restart: always