version: "3.7"
services:
  tomcat:
    build: ./images/tomcat
    network_mode: "host"
    depends_on:
      - mysql
      - redis
    restart: always
  flyway:
    image: flyway/flyway:6-alpine
    volumes:
      - ./services/flyway/sql:/flyway/sql
      - ./services/flyway/conf:/flyway/conf
    command: -connectRetries=60 migrate
    network_mode: "host"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: programmingroad
    volumes:
      - ./services/mysql/volume:/var/lib/mysql
    network_mode: "host"
    restart: always
  redis:
    image: redis:6.0-rc-alpine
    network_mode: "host"
    restart: always