version: "3.7"
services:
  nginx:
    image: nginx:1.17-alpine
    volumes:
      - ./services/nginx/build:/usr/share/nginx/html
      - ./services/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /etc/localtime:/etc/localtime
    network_mode: "host"
    depends_on:
      - server
    restart: always
  server:
    build: ./images/server
    image: server
    volumes:
      - ./services/server:/server
      - /etc/localtime:/etc/localtime
    network_mode: "host"
    depends_on:
      - mysql
      - redis
    restart: always
  flyway:
    image: flyway/flyway:6-alpine
    volumes:
      - ./services/flyway/sql:/flyway/sql
      - ./services/flyway/conf:/flyway/conf
      - /etc/localtime:/etc/localtime
    command: -connectRetries=60 migrate
    network_mode: "host"
    depends_on:
      - mysql
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: programmingroad
    volumes:
      - ./services/mysql/volume:/var/lib/mysql
      - /etc/localtime:/etc/localtime
    network_mode: "host"
    restart: always
  redis:
    image: redis:6.0-rc-alpine
    volumes:
      - /etc/localtime:/etc/localtime
    network_mode: "host"
    restart: always